### ISSUE TITLE
feat: Implement continuous security scanning

### ISSUE THREAD

**Issue by lmlong-huynh** [HMS-Kontoret/.github#13]
## Description
Investigate whether our security scanning measures are sufficient as of current.Could we be more vigilant? Activate auto-PR creation for Dependabot in GitHub, periodic Docker image analysis?Are we able to react timely upon the advice we get from the scanners? 

## Acceptance criteria
TBD

## Additional context
[Related issue](https://stamina.atlassian.net/wiki/spaces/PD/pages/2287370342/DevOps+Priorities)

**Comment by mauritz-lovgren** [comment]
@lena-osterhus : link JIRA issue here!

**Comment by lena-osterhus** [comment]
https://stamina.atlassian.net/browse/ADAT-1497

**Comment by mauritz-lovgren** [comment]
Is this solved for all projects now?
